In [ ]:
Employee Salary Analysis

In [ ]:
import pandas as pd
salary = pd.read_csv("/content/employee_salary_dataset.csv")
salary.head()

,EmployeeID,Name,Department,Experience_Years,Education_Level,Age,Gender,City,Monthly_Salary
0,1,Employee_1,Marketing,15,Master,53,Female,Delhi,111416
1,2,Employee_2,Operations,7,Bachelor,25,Female,Bangalore,95271
2,3,Employee_3,IT,12,High School,51,Female,Hyderabad,69064
3,4,Employee_4,Operations,8,PhD,44,Male,Delhi,95091
4,5,Employee_5,Operations,15,Master,36,Female,Delhi,132450

In [ ]:
sorted_column = salary.sort_values(by='Department')
sorted_column

,EmployeeID,Name,Department,Experience_Years,Education_Level,Age,Gender,City,Monthly_Salary
15,16,Employee_16,Finance,4,High School,49,Female,Delhi,101213
46,47,Employee_47,Finance,3,Master,22,Female,Delhi,58828
27,28,Employee_28,Finance,16,Master,29,Female,Hyderabad,118179
48,49,Employee_49,Finance,5,PhD,23,Female,Hyderabad,28420
44,45,Employee_45,Finance,8,Master,53,Male,Delhi,57635
5,6,Employee_6,Finance,3,High School,50,Male,Mumbai,65818
20,21,Employee_21,Finance,4,Master,46,Female,Delhi,73404
43,44,Employee_44,Finance,17,Master,44,Male,Hyderabad,72202
39,40,Employee_40,Finance,12,Bachelor,38,Female,Mumbai,68484
13,14,Employee_14,Finance,6,Bachelor,27,Male,Delhi,28436
23,24,Employee_24,HR,15,Master,48,Male,Bangalore,64790
33,34,Employee_34,HR,15,Bachelor,53,Female,Delhi,134616
18,19,Employee_19,HR,2,PhD,32,Male,Chennai,55746
38,39,Employee_39,HR,1,Master,24,Male,Mumbai,43589
24,25,Employee_25,HR,8,High School,34,Female,Bangalore,132455
41,42,Employee_42,HR,11,PhD,23,Male,Chennai,61212
45,46,Employee_46,HR,3,PhD,54,Female,Hyderabad,88208
11,12,Employee_12,IT,4,Master,49,Female,Hyderabad,104909
36,37,Employee_37,IT,7,High School,33,Male,Chennai,81491
8,9,Employee_9,IT,4,Bachelor,53,Male,Hyderabad,42429
34,35,Employee_35,IT,13,Master,53,Male,Bangalore,130983
7,8,Employee_8,IT,17,PhD,34,Female,Bangalore,44830
6,7,Employee_7,IT,14,PhD,57,Male,Mumbai,70525
25,26,Employee_26,IT,14,Master,24,Male,Hyderabad,30600
26,27,Employee_27,IT,8,Bachelor,27,Female,Delhi,119660
2,3,Employee_3,IT,12,High School,51,Female,Hyderabad,69064
30,31,Employee_31,IT,15,Bachelor,54,Female,Hyderabad,70714
31,32,Employee_32,Marketing,13,Master,45,Female,Hyderabad,81835
42,43,Employee_43,Marketing,19,High School,49,Female,Delhi,68525
32,33,Employee_33,Marketing,9,Master,36,Male,Bangalore,127946
40,41,Employee_41,Marketing,8,Bachelor,23,Female,Bangalore,107989
0,1,Employee_1,Marketing,15,Master,53,Female,Delhi,111416
28,29,Employee_29,Marketing,13,High School,48,Male,Bangalore,65764
10,11,Employee_11,Marketing,8,PhD,43,Male,Delhi,141381
29,30,Employee_30,Marketing,18,High School,30,Male,Delhi,99543
16,17,Employee_17,Marketing,18,Master,41,Female,Hyderabad,30895
14,15,Employee_15,Marketing,10,PhD,49,Female,Mumbai,99290
22,23,Employee_23,Marketing,16,High School,22,Male,Bangalore,122888
19,20,Employee_20,Marketing,10,Bachelor,49,Male,Bangalore,74377
49,50,Employee_50,Marketing,10,High School,47,Female,Bangalore,121752
37,38,Employee_38,Operations,9,Master,23,Male,Mumbai,149123
17,18,Employee_18,Operations,12,PhD,51,Female,Chennai,44738
35,36,Employee_36,Operations,1,Master,45,Female,Delhi,98744
21,22,Employee_22,Operations,14,Master,54,Female,Delhi,79045
12,13,Employee_13,Operations,2,Master,23,Female,Hyderabad,72333
9,10,Employee_10,Operations,18,High School,28,Male,Mumbai,31893
4,5,Employee_5,Operations,15,Master,36,Female,Delhi,132450
3,4,Employee_4,Operations,8,PhD,44,Male,Delhi,95091
1,2,Employee_2,Operations,7,Bachelor,25,Female,Bangalore,95271
47,48,Employee_48,Operations,1,High School,40,Male,Chennai,43711

In [ ]:
Average_salary = salary.groupby('Department')['Monthly_Salary'].mean()
Average_salary

Department
Finance       67261.900000
HR            82945.142857
IT            76520.500000
Marketing     96430.846154
Operations    84239.900000
Name: Monthly_Salary, dtype: float64

In [ ]:

highest_paid_employee = salary.loc[salary['Monthly_Salary'].idxmax()]

lowest_paid_employee = salary.loc[salary['Monthly_Salary'].idxmin()]

print("Highest Paid Employee:")
display(highest_paid_employee)

print("\nLowest Paid Employee:")
display(lowest_paid_employee)

Highest Paid Employee:

EmployeeID                   38
Name                Employee_38
Department           Operations
Experience_Years              9
Education_Level          Master
Age                          23
Gender                     Male
City                     Mumbai
Monthly_Salary           149123
Name: 37, dtype: object

Lowest Paid Employee:

EmployeeID                   49
Name                Employee_49
Department              Finance
Experience_Years              5
Education_Level             PhD
Age                          23
Gender                   Female
City                  Hyderabad
Monthly_Salary            28420
Name: 48, dtype: object

In [ ]:
average_salary_by_gender = salary.groupby('Gender')['Monthly_Salary'].mean()
display(average_salary_by_gender)

Gender
Female    87306.185185
Male      76398.826087
Name: Monthly_Salary, dtype: float64

In [ ]:
salary.describe()

       EmployeeID  Experience_Years        Age  Monthly_Salary
count    50.00000         50.000000  50.000000         50.0000
mean     25.50000          9.900000  39.760000      82288.8000
std      14.57738          5.349995  11.539745      33521.4379
min       1.00000          1.000000  22.000000      28420.0000
25%      13.25000          5.250000  28.250000      59424.0000
50%      25.50000         10.000000  43.500000      73890.5000
75%      37.75000         14.750000  49.000000     107219.0000
max      50.00000         19.000000  57.000000     149123.0000